spring:
  application:
    name: facv-loader-service
  datasource:
    # SQL Developer connection from screenshot:
    # Hostname=localhost, Port=1521, Service name=XEPDB1, Username=system
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: system
    password: System@123
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: never

loader:
  enabled: true
  run-on-startup: false
  # Local machine default (no export needed)
  incoming-path: ${user.home}/Documents/hub/var/incoming
  success-path: ${user.home}/Documents/hub/var/success
  failed-path: ${user.home}/Documents/hub/var/failed
  file-names:
    - CLFACV.txt
    - CLFACVHASE.txt
  charset: UTF-8
  batch-size: 1000
  # Every 5 minutes for testing
  schedule-cron: "0 */5 * * * *"
  schedule-zone: Asia/Hong_Kong

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.loader.facv: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
