-- Run this script as DBA user (SYS/SYSTEM) in SQL Developer.
-- Update values before running.

DEFINE APP_SCHEMA = LOADER_APP
DEFINE APP_PASSWORD = Loader@123

CREATE USER &&APP_SCHEMA
  IDENTIFIED BY "&&APP_PASSWORD"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;

ALTER USER &&APP_SCHEMA QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &&APP_SCHEMA;
GRANT CREATE TABLE TO &&APP_SCHEMA;
GRANT CREATE SEQUENCE TO &&APP_SCHEMA;
GRANT CREATE VIEW TO &&APP_SCHEMA;

-- Optional: for troubleshooting object metadata access
GRANT SELECT_CATALOG_ROLE TO &&APP_SCHEMA;
