CREATE TABLE STG_HK_OBS_FACV (
    BNK_NO CHAR(3),
    CUST_ACCT_NO CHAR(12),
    SYS_COD CHAR(3),
    REC_TYPE CHAR(1),
    CUST_GP CHAR(1),
    ITL_CUST_NO CHAR(11),
    FILLER CHAR(11),
    LMT_ID CHAR(5),
    CUST_ID CHAR(11),
    FILLER1 CHAR(7),
    MAINT_ACT CHAR(1)
);
