CREATE TABLE STG_HK_OBS_FACV (
    BNK_NO CHAR(3) NULL,
    CUST_ACCT_NO CHAR(12) NULL,
    SYS_COD CHAR(3) NULL,
    REC_TYPE CHAR(1) NULL,
    CUST_GP CHAR(1) NULL,
    ITL_CUST_NO CHAR(11) NULL,
    FILLER CHAR(11) NULL,
    LMT_ID CHAR(5) NULL,
    CUST_ID CHAR(11) NULL,
    FILLER1 CHAR(7) NULL,
    MAINT_ACT CHAR(1) NULL
);
