CREATE TABLE STG_HK_OBS_FACV (
    BNK_NO VARCHAR2(3),
    CUST_ACCT_NO VARCHAR2(12),
    SYS_CODE VARCHAR2(3),
    REC_TYPE VARCHAR2(1),
    CUST_GP VARCHAR2(1),
    ITL_CUST_NO VARCHAR2(11),
    FILLER VARCHAR2(11),
    LMT_ID VARCHAR2(5),
    CUST_ID VARCHAR2(11),
    FILLER1 VARCHAR2(7),
    MAINT_ACCT VARCHAR2(1)
);
